#pragma once

#include "wx/wx.h"


enum CUSTOM_CTROL_ID
{
    ID_AC_BUTTON = 3200,
    ID_DIALOG_TOP_BAR,
    ID_CONFIGURATION,
    ID_TOP_FILE_MENU,
    ID_TOP_EDIT_MENU,
    ID_TOP_VIEW_MENU,
    ID_TOP_SETS_MENU,
    ID_TOP_HELP_MENU,
    ID_LOGO,
    ID_TITLE,
    ID_TOP_BAR,
    ID_TOOL_BAR,
};

#define AC_COLOR_BOARD_GRAY          wxColour(214, 220, 230)

#define AC_COLOR_FONT_GRAY         wxColour(142, 153, 173)

#define AC_COLOR_PANEL_BG			 wxColour(240, 243, 247) 
#define AC_COLOR_ITEM_HOVER	         wxColour(231, 240, 255)
// main blue 
#define AC_COLOR_MAIN_BLUE           wxColour(57, 134, 255)
#define AC_COLOR_MAIN_BLUE_HOVER	 wxColour(95, 157, 255)
#define AC_COLOR_MAIN_BLUE_PRESSED   wxColour(29, 105, 224)
#define AC_COLOR_MAIN_BLUE_DISABLE   wxColour(189, 214, 252)

#define AC_COLOR_MAIN_BLUE_TRANS_TWO wxColour(175, 206, 255)
#define AC_COLOR_MAIN_BLUE_TRANS_HOVER wxColour(215, 231, 255)

#define AC_COLOR_BOX_GRAY  wxColour(209, 210, 213) 
#define AC_COLOR_CHECKBOX_GRAY  AC_COLOR_BOX_GRAY

#define AC_COLOR_LIGHTBLUE       wxColour(204, 224, 255)
// text default white
#define AC_COLOR_WHITE           wxColour(255,255,255)
// text default black
#define AC_COLOR_BLACK           wxColour(20, 28, 41 )
#define AC_COLOR_BLACK_DISABLE   wxColour(151, 158, 168 )
#define AC_COLOR_BLACK_GRAY     wxColour(112, 112, 112)
// for mainframe toolbar / settings Tab
#define AC_COLOR_PAGE_BLACK           wxColour(60, 79, 115)
#define AC_COLOR_PAGE_BLACK_DISABLE   wxColour(168, 168, 168)
// for mainframe left panel button / dropdown item
#define AC_COLOR_ITEM_BLACK           wxColour(77, 77, 77 )
// default blue
#define AC_COLOR_BLUE_NORMAL    AC_COLOR_MAIN_BLUE
#define AC_COLOR_BLUE_HOVER	    AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_BLUE_PRESSED   AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_BLUE_DISABLE   AC_COLOR_MAIN_BLUE_DISABLE
// black to white
#define AC_COLOR_BK2WHITE_NORMAL   AC_COLOR_BLACK
#define AC_COLOR_BK2WHITE_HOVER	   AC_COLOR_BLACK
#define AC_COLOR_BK2WHITE_PRESSED  AC_COLOR_BLACK
#define AC_COLOR_BK2WHITE_SELECT   AC_COLOR_WHITE
// black to blue
#define AC_COLOR_BK2BLUE_NORMAL   AC_COLOR_BLACK
#define AC_COLOR_BK2BLUE_HOVER	  AC_COLOR_BLUE_NORMAL
#define AC_COLOR_BK2BLUE_PRESSED  AC_COLOR_BLUE_PRESSED
#define AC_COLOR_BK2BLUE_SELECT   AC_COLOR_WHITE
#define AC_COLOR_BK2BLUE_DISABLE  AC_COLOR_PAGE_BLACK_DISABLE

// black to blue level up
#define AC_COLOR_BK2BLUE_LU_NORMAL   AC_COLOR_PAGE_BLACK
#define AC_COLOR_BK2BLUE_LU_HOVER	 AC_COLOR_BLUE_NORMAL
#define AC_COLOR_BK2BLUE_LU_PRESSED  AC_COLOR_BLUE_PRESSED
#define AC_COLOR_BK2BLUE_LU_SELECT   AC_COLOR_WHITE

#define AC_COLOR_BK2BLUE_LU_NORMAL   AC_COLOR_PAGE_BLACK
#define AC_COLOR_BK2BLUE_LU_HOVER	 AC_COLOR_BLUE_NORMAL
#define AC_COLOR_BK2BLUE_LU_PRESSED  AC_COLOR_BLUE_PRESSED
#define AC_COLOR_BK2BLUE_LU_SELECT   AC_COLOR_WHITE

// background main


// background transpan to light blue 

// background transpan to blue 

#define AC_COLOR_WHITEBLUE         wxColour(244, 248, 254)
#define AC_COLOR_WHITEBLUE_HOVER   wxColour(255, 255, 255)
#define AC_COLOR_WHITEBLUE_PRESSED wxColour(240, 244, 250)
#define AC_COLOR_WHITEBLUE_DISABLE wxColour(244, 248, 254)
// 
#define AC_COLOR_BG_WHITE         wxColour(255, 255, 255)
#define AC_COLOR_BG_WHITE_HOVER   wxColour(244, 248, 254)
#define AC_COLOR_BG_WHITE_PRESSED wxColour(235, 239, 245)
#define AC_COLOR_BG_WHITE_DISABLE wxColour(244, 244, 244)

// border
#define AC_COLOR_BD_BLACK         wxColour(175, 185, 204)
#define AC_COLOR_BD_BLUE_HOVER    wxColour(153, 192, 255)
#define AC_COLOR_BD_BLUE_PRESSED  wxColour(29, 105, 224)
#define AC_COLOR_BD_BLACK_DISABLE wxColour(217, 217, 217)


/*--START BUTTON--*/

#define AC_COLOR_BT_L0_BG_NOR AC_COLOR_MAIN_BLUE        
#define AC_COLOR_BT_L0_BG_HOV AC_COLOR_MAIN_BLUE_HOVER	
#define AC_COLOR_BT_L0_BG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_BT_L0_BG_DIS AC_COLOR_MAIN_BLUE_DISABLE
#define AC_COLOR_BT_L0_BD_NOR AC_COLOR_BT_L0_BG_NOR
#define AC_COLOR_BT_L0_BD_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_L0_BD_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_L0_BD_DIS AC_COLOR_BT_L0_BG_DIS
#define AC_COLOR_BT_L0_FG_NOR AC_COLOR_WHITE
#define AC_COLOR_BT_L0_FG_HOV AC_COLOR_WHITE
#define AC_COLOR_BT_L0_FG_PRE AC_COLOR_WHITE
#define AC_COLOR_BT_L0_FG_DIS AC_COLOR_WHITE

#define AC_COLOR_BT_L1_BG_NOR AC_COLOR_WHITEBLUE        
#define AC_COLOR_BT_L1_BG_HOV AC_COLOR_WHITEBLUE_HOVER	
#define AC_COLOR_BT_L1_BG_PRE AC_COLOR_WHITEBLUE_PRESSED
#define AC_COLOR_BT_L1_BG_DIS AC_COLOR_WHITEBLUE_DISABLE
#define AC_COLOR_BT_L1_BD_NOR AC_COLOR_BT_L0_BG_NOR
#define AC_COLOR_BT_L1_BD_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_L1_BD_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_L1_BD_DIS AC_COLOR_BT_L0_BG_DIS
#define AC_COLOR_BT_L1_FG_NOR AC_COLOR_BT_L0_BG_NOR
#define AC_COLOR_BT_L1_FG_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_L1_FG_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_L1_FG_DIS AC_COLOR_BT_L0_BG_DIS

#define AC_COLOR_BT_L2_BG_NOR AC_COLOR_BG_WHITE        
#define AC_COLOR_BT_L2_BG_HOV AC_COLOR_BG_WHITE_HOVER  
#define AC_COLOR_BT_L2_BG_PRE AC_COLOR_BG_WHITE_PRESSED
#define AC_COLOR_BT_L2_BG_DIS AC_COLOR_BG_WHITE_DISABLE
#define AC_COLOR_BT_L2_BD_NOR AC_COLOR_BT_L0_BG_NOR
#define AC_COLOR_BT_L2_BD_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_L2_BD_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_L2_BD_DIS AC_COLOR_BT_L0_BG_DIS
#define AC_COLOR_BT_L2_FG_NOR AC_COLOR_PAGE_BLACK
#define AC_COLOR_BT_L2_FG_HOV AC_COLOR_PAGE_BLACK
#define AC_COLOR_BT_L2_FG_PRE AC_COLOR_PAGE_BLACK
#define AC_COLOR_BT_L2_FG_DIS AC_COLOR_PAGE_BLACK_DISABLE

#define AC_COLOR_BT_L3_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BG_PRE AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BG_DIS AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BD_NOR AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BD_HOV AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BD_PRE AC_COLOR_WHITE
#define AC_COLOR_BT_L3_BD_DIS AC_COLOR_WHITE
#define AC_COLOR_BT_L3_FG_NOR AC_COLOR_BT_L0_BG_NOR
#define AC_COLOR_BT_L3_FG_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_L3_FG_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_L3_FG_DIS AC_COLOR_BT_L0_BG_DIS

// switch Not Sel
//#define AC_COLOR_BT_L0N_BG_NOR AC_COLOR_WHITE
//#define AC_COLOR_BT_L0N_BG_HOV AC_COLOR_WHITE
//#define AC_COLOR_BT_L0N_BG_PRE AC_COLOR_WHITE
//#define AC_COLOR_BT_L0N_BG_DIS AC_COLOR_BT_L2_BG_DIS
//#define AC_COLOR_BT_L0N_BD_NOR AC_COLOR_WHITE
//#define AC_COLOR_BT_L0N_BD_HOV AC_COLOR_BD_BLUE_HOVER
//#define AC_COLOR_BT_L0N_BD_PRE AC_COLOR_BD_BLUE_PRESSED
//#define AC_COLOR_BT_L0N_BD_DIS AC_COLOR_BT_L2_BD_DIS
#define AC_COLOR_BT_L0N_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_BT_L0N_FG_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_BT_L0N_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_BT_L0N_FG_DIS AC_COLOR_BT_L2_FG_DIS

// 
#define AC_COLOR_BT_SEL_BG_NOR AC_COLOR_BT_L2_BG_NOR
#define AC_COLOR_BT_SEL_BG_HOV AC_COLOR_BT_L0_BG_HOV
#define AC_COLOR_BT_SEL_BG_PRE AC_COLOR_BT_L0_BG_PRE
#define AC_COLOR_BT_SEL_BG_DIS AC_COLOR_BT_L2_BG_DIS
#define AC_COLOR_BT_SEL_BD_NOR AC_COLOR_BT_L2_BD_NOR
#define AC_COLOR_BT_SEL_BD_HOV AC_COLOR_BT_L0_BD_HOV
#define AC_COLOR_BT_SEL_BD_PRE AC_COLOR_BT_L0_BD_HOV
#define AC_COLOR_BT_SEL_BD_DIS AC_COLOR_BT_L2_BD_DIS
#define AC_COLOR_BT_SEL_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_BT_SEL_FG_HOV AC_COLOR_WHITE
#define AC_COLOR_BT_SEL_FG_PRE AC_COLOR_WHITE
#define AC_COLOR_BT_SEL_FG_DIS AC_COLOR_BT_L2_FG_DIS

// check
#define AC_COLOR_ITEM_BG wxColour(235, 243, 255)

#define AC_COLOR_BT_CHECK_L0_BG_NOR AC_COLOR_ITEM_BG
#define AC_COLOR_BT_CHECK_L0_BG_CHK AC_COLOR_MAIN_BLUE
#define AC_COLOR_BT_CHECK_L0_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_BT_CHECK_L0_FG_CHK AC_COLOR_WHITE

#define AC_COLOR_BT_CHECK_L1_BG_NOR AC_COLOR_ITEM_BG
#define AC_COLOR_BT_CHECK_L1_BG_CHK AC_COLOR_ITEM_BG
#define AC_COLOR_BT_CHECK_L1_BD_NOR AC_COLOR_ITEM_BG
#define AC_COLOR_BT_CHECK_L1_BD_CHK AC_COLOR_MAIN_BLUE
#define AC_COLOR_BT_CHECK_L1_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_BT_CHECK_L1_FG_CHK AC_COLOR_MAIN_BLUE

/*--END BUTTON--*/

/*--START MAINFRAM LIST ITEM--*/

#define AC_COLOR_MLIST_ITEM_NORMAL AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_HOVER  wxColour(230, 240, 255)
#define AC_COLOR_MLIST_ITEM_PRESS  AC_COLOR_LIGHTBLUE
#define AC_COLOR_MLIST_ITEM_SELECT wxColour(128, 176, 255)

#define AC_COLOR_MLIST_ITEM_L0_BG_NOR AC_COLOR_MLIST_ITEM_NORMAL
#define AC_COLOR_MLIST_ITEM_L0_BG_HOV AC_COLOR_MLIST_ITEM_HOVER 
#define AC_COLOR_MLIST_ITEM_L0_BG_PRE AC_COLOR_MLIST_ITEM_PRESS 
#define AC_COLOR_MLIST_ITEM_L0_BG_SEL AC_COLOR_MLIST_ITEM_SELECT
#define AC_COLOR_MLIST_ITEM_L0_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_MLIST_ITEM_L0_FG_HOV AC_COLOR_BLACK 
#define AC_COLOR_MLIST_ITEM_L0_FG_PRE AC_COLOR_BLACK 
#define AC_COLOR_MLIST_ITEM_L0_FG_SEL AC_COLOR_WHITE

#define AC_COLOR_MLIST_ITEM_L1_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L1_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L1_BG_PRE AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L1_BG_SEL AC_COLOR_MAIN_BLUE
#define AC_COLOR_MLIST_ITEM_L1_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_MLIST_ITEM_L1_FG_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_MLIST_ITEM_L1_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_MLIST_ITEM_L1_FG_SEL AC_COLOR_WHITE

#define AC_COLOR_MLIST_ITEM_L2_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L2_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L2_BG_PRE AC_COLOR_WHITE
#define AC_COLOR_MLIST_ITEM_L2_BG_SEL AC_COLOR_MAIN_BLUE
#define AC_COLOR_MLIST_ITEM_L2_FG_NOR AC_COLOR_PAGE_BLACK
#define AC_COLOR_MLIST_ITEM_L2_FG_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_MLIST_ITEM_L2_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_MLIST_ITEM_L2_FG_SEL AC_COLOR_WHITE

/*--END MAINFRAM LIST ITEM--*/


/*--START DROPDOWN--*/
#define AC_COLOR_BG_LIGHTGRAY wxColour(247, 249, 252)
#define AC_COLOR_BG_LIGHTGRAY_DISABLE AC_COLOR_BG_WHITE_DISABLE
#define AC_COLOR_BG_LIGHTGRAY_BD         wxColour(195, 204, 217)
#define AC_COLOR_BG_LIGHTGRAY_BD_DISABLE wxColour(195, 204, 217)

#define AC_COLOR_BG_LIGHTGRAY_ITEM_DISABLE wxColour(245, 245, 245)

#define AC_COLOR_DROPDOWN_BG_NOR AC_COLOR_BG_LIGHTGRAY
#define AC_COLOR_DROPDOWN_BG_HOV AC_COLOR_BG_LIGHTGRAY
#define AC_COLOR_DROPDOWN_BG_PRE AC_COLOR_BG_LIGHTGRAY
#define AC_COLOR_DROPDOWN_BG_SEL AC_COLOR_BG_LIGHTGRAY
#define AC_COLOR_DROPDOWN_BG_DIS AC_COLOR_BG_LIGHTGRAY_ITEM_DISABLE
#define AC_COLOR_DROPDOWN_BD_NOR AC_COLOR_BG_LIGHTGRAY_BD
#define AC_COLOR_DROPDOWN_BD_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_DROPDOWN_BD_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_DROPDOWN_BD_SEL AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_DROPDOWN_BD_DIS AC_COLOR_BG_LIGHTGRAY_BD_DISABLE
#define AC_COLOR_DROPDOWN_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_DROPDOWN_FG_HOV AC_COLOR_BLACK
#define AC_COLOR_DROPDOWN_FG_PRE AC_COLOR_BLACK
#define AC_COLOR_DROPDOWN_FG_SEL AC_COLOR_BLACK
#define AC_COLOR_DROPDOWN_FG_DIS AC_COLOR_BLACK_DISABLE
// DROPDOWN ITEM
#define AC_COLOR_DROPDOWN_ITEM_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_DROPDOWN_ITEM_BG_HOV AC_COLOR_ITEM_HOVER
#define AC_COLOR_DROPDOWN_ITEM_BG_SEL AC_COLOR_BG_LIGHTGRAY_ITEM_DISABLE
//#define AC_COLOR_DROPDOWN_ITEM_BG_PRE AC_COLOR_BG_LIGHTGRAY
//#define AC_COLOR_DROPDOWN_ITEM_BG_SEL AC_COLOR_BG_LIGHTGRAY
//#define AC_COLOR_DROPDOWN_ITEM_BG_DIS AC_COLOR_BG_LIGHTGRAY
// DROPDOWN ITEM PREV SEL
/*--START DROPDOWN--*/

/*--START TEXTINPUT--*/
#define AC_COLOR_TEXTINPUT_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_TEXTINPUT_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_TEXTINPUT_BG_PRE AC_COLOR_WHITE
#define AC_COLOR_TEXTINPUT_BG_DIS AC_COLOR_BG_WHITE_DISABLE
#define AC_COLOR_TEXTINPUT_BD_NOR AC_COLOR_BG_LIGHTGRAY_BD
#define AC_COLOR_TEXTINPUT_BD_HOV AC_COLOR_BD_BLUE_HOVER
#define AC_COLOR_TEXTINPUT_BD_PRE AC_COLOR_BD_BLUE_PRESSED
#define AC_COLOR_TEXTINPUT_BD_DIS AC_COLOR_BG_LIGHTGRAY_BD_DISABLE
#define AC_COLOR_TEXTINPUT_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_TEXTINPUT_FG_HOV AC_COLOR_BLACK
#define AC_COLOR_TEXTINPUT_FG_PRE AC_COLOR_BLACK
#define AC_COLOR_TEXTINPUT_FG_DIS AC_COLOR_BLACK_DISABLE


/*--END TEXTINPUT--*/

/*--START SPINBOX--*/
#define AC_COLOR_SPINBOX_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_SPINBOX_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_SPINBOX_BG_PRE AC_COLOR_WHITE
#define AC_COLOR_SPINBOX_BG_SEL AC_COLOR_WHITE
#define AC_COLOR_SPINBOX_BG_DIS AC_COLOR_BG_WHITE_DISABLE
#define AC_COLOR_SPINBOX_BD_NOR AC_COLOR_BG_LIGHTGRAY_BD
#define AC_COLOR_SPINBOX_BD_HOV AC_COLOR_BD_BLUE_HOVER
#define AC_COLOR_SPINBOX_BD_PRE AC_COLOR_BD_BLUE_PRESSED
#define AC_COLOR_SPINBOX_BD_SEL AC_COLOR_BD_BLUE_PRESSED
#define AC_COLOR_SPINBOX_BD_DIS AC_COLOR_BG_LIGHTGRAY_BD_DISABLE
#define AC_COLOR_SPINBOX_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_SPINBOX_FG_HOV AC_COLOR_BLACK
#define AC_COLOR_SPINBOX_FG_PRE AC_COLOR_BLACK
#define AC_COLOR_SPINBOX_FG_SEL AC_COLOR_BLACK
#define AC_COLOR_SPINBOX_FG_DIS AC_COLOR_BLACK_DISABLE

#define AC_COLOR_SEL_BG wxColour(181, 210, 255)
#define AC_COLOR_SPINBOX_SEL_BG_NOR AC_COLOR_SEL_BG

//#define AC_COLOR_SPINBOX_SPIN_BG_NOR AC_COLOR_WHITE
//#define AC_COLOR_SPINBOX_SPIN_BG_HOV AC_COLOR_ITEM_HOVER
//#define AC_COLOR_SPINBOX_SPIN_BG_PRE AC_COLOR_ITEM_PRESS

/*--END SPINBOX--*/

/*--START CHECKBOX--*/
#define AC_COLOR_CHECKBOX_BG_NOR AC_COLOR_MAIN_BLUE
#define AC_COLOR_CHECKBOX_BG_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_CHECKBOX_BG_DIS AC_COLOR_BG_LIGHTGRAY_ITEM_DISABLE
#define AC_COLOR_CHECKBOX_BD_NOR AC_COLOR_MAIN_BLUE
#define AC_COLOR_CHECKBOX_BD_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_CHECKBOX_BD_DIS AC_COLOR_BG_LIGHTGRAY_BD

#define AC_COLOR_CHECKBOX_N_BG_NOR AC_COLOR_WHITE
#define AC_COLOR_CHECKBOX_N_BG_HOV AC_COLOR_WHITE
#define AC_COLOR_CHECKBOX_N_BG_DIS AC_COLOR_BG_LIGHTGRAY_ITEM_DISABLE
#define AC_COLOR_CHECKBOX_N_BD_NOR AC_COLOR_BG_LIGHTGRAY_BD
#define AC_COLOR_CHECKBOX_N_BD_HOV AC_COLOR_MAIN_BLUE
#define AC_COLOR_CHECKBOX_N_BD_DIS AC_COLOR_BG_LIGHTGRAY_BD

/*--END CHECKBOX--*/

/*--START TAB--*/
#define AC_COLOR_MAIN_BLUE_TAB_HOVER	 wxColour(57, 134, 255)

#define AC_COLOR_TAB_BG				     AC_COLOR_ITEM_HOVER

#define AC_COLOR_TAB_ITEM_BG_NOR AC_COLOR_TAB_BG
#define AC_COLOR_TAB_ITEM_BG_SEL AC_COLOR_WHITE

#define AC_COLOR_TAB_ITEM_FG_NOR AC_COLOR_PAGE_BLACK
#define AC_COLOR_TAB_ITEM_FG_HOV AC_COLOR_MAIN_BLUE_TAB_HOVER
#define AC_COLOR_TAB_ITEM_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_TAB_ITEM_FG_SEL AC_COLOR_MAIN_BLUE

/*--END TAB--*/

/*--START SWITCH--*/
#define AC_COLOR_SWITCH_BG wxColour(240, 242, 245)

#define AC_COLOR_SWITCH_BG_NOR AC_COLOR_SWITCH_BG
#define AC_COLOR_SWITCH_BG_SEL AC_COLOR_MAIN_BLUE
#define AC_COLOR_SWITCH_FG_NOR AC_COLOR_PAGE_BLACK
#define AC_COLOR_SWITCH_FG_HOV AC_COLOR_MAIN_BLUE
#define AC_COLOR_SWITCH_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_SWITCH_FG_SEL AC_COLOR_WHITE
/*--END SWITCH--*/

/*--START SELECT IMAGE--*/
#define AC_COLOR_SEL_IMG wxColour(220, 224, 230)

#define AC_COLOR_SEL_IMG_BG AC_COLOR_WHITE

#define AC_COLOR_SEL_IMG_BD_NOR AC_COLOR_SEL_IMG
#define AC_COLOR_SEL_IMG_BD_HOV AC_COLOR_MAIN_BLUE_HOVER
#define AC_COLOR_SEL_IMG_BD_PRE AC_COLOR_MAIN_BLUE_PRESSED
#define AC_COLOR_SEL_IMG_BD_SEL AC_COLOR_MAIN_BLUE
#define AC_COLOR_SEL_IMG_BD_DIS AC_COLOR_MAIN_BLUE_DISABLE

#define AC_COLOR_SEL_IMG_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_SEL_IMG_FG_HOV AC_COLOR_SEL_IMG_BD_HOV
#define AC_COLOR_SEL_IMG_FG_PRE AC_COLOR_SEL_IMG_BD_PRE
#define AC_COLOR_SEL_IMG_FG_SEL AC_COLOR_SEL_IMG_BD_SEL
#define AC_COLOR_SEL_IMG_FG_DIS AC_COLOR_SEL_IMG_BD_DIS

/*--END SELECT IMAGE--*/


/*--START SLIDER--*/
#define AC_COLOR_SLIDER_BG wxColour(197, 204, 219)
#define AC_COLOR_SLIDER_BT_BD wxColour(198, 200, 204)


#define AC_COLOR_SLIDER_BG_NOR AC_COLOR_SLIDER_BG
#define AC_COLOR_SLIDER_BG_SEL AC_COLOR_MAIN_BLUE

#define AC_COLOR_SLIDER_BT_BG AC_COLOR_WHITE

#define AC_COLOR_SLIDER_BT_BD_NOR AC_COLOR_SLIDER_BT_BG
#define AC_COLOR_SLIDER_BT_BD_SEL AC_COLOR_MAIN_BLUE

/*--END SLIDER--*/

/*--START PROGRESS--*/
#define AC_COLOR_PROGRESS_BG wxColour(169, 177, 193)
#define AC_COLOR_PROGRESS_BT_TRANSP wxColour(255,255,255,0)

#define AC_COLOR_PROGRESS_BG_NOR AC_COLOR_PROGRESS_BG
#define AC_COLOR_PROGRESS_BG_SEL AC_COLOR_MAIN_BLUE

#define AC_COLOR_PROGRESS_BT_BG  AC_COLOR_WHITE
#define AC_COLOR_PROGRESS_BT_BG_SEL AC_COLOR_MAIN_BLUE
#define AC_COLOR_PROGRESS_BT_BG_DIS AC_COLOR_MAIN_BLUE_DISABLE

#define AC_COLOR_PROGRESS_BT_BD  AC_COLOR_MAIN_BLUE
#define AC_COLOR_PROGRESS_BT_BD_SEL AC_COLOR_PROGRESS_BT_TRANSP
#define AC_COLOR_PROGRESS_BT_BD_DIS AC_COLOR_PROGRESS_BT_TRANSP

/*--END PROGRESS--*/

/*--START LISTBOX--*/


#define AC_COLOR_LISTBOX_ITEM_BG_NOR AC_COLOR_PANEL_BG
#define AC_COLOR_LISTBOX_ITEM_BG_HOV AC_COLOR_PANEL_BG 
#define AC_COLOR_LISTBOX_ITEM_BG_PRE AC_COLOR_PANEL_BG 
#define AC_COLOR_LISTBOX_ITEM_BG_SEL AC_COLOR_MAIN_BLUE

#define AC_COLOR_LISTBOX_ITEM_FG_NOR AC_COLOR_BLACK
#define AC_COLOR_LISTBOX_ITEM_FG_HOV AC_COLOR_MAIN_BLUE_HOVER 
#define AC_COLOR_LISTBOX_ITEM_FG_PRE AC_COLOR_MAIN_BLUE_PRESSED 
#define AC_COLOR_LISTBOX_ITEM_FG_SEL AC_COLOR_WHITE

/*--END LISTBOX--*/
